### ISSUE TITLE
Uncaught Error: Can't select in removed DomRangeDOMRange

### ISSUE THREAD

**Issue by richieroldan** [abecks/meteor-infinite-scroll#15]
Whenever I go to another page I'm getting this error whenever I scroll in page.
![screenshot](https://cloud.githubusercontent.com/assets/9613793/20654505/1f2a3e30-b555-11e6-8296-8bec1ab8a046.png)

Thanks

**Comment by abecks** [comment]
Can you please create a repository to show the issue? With the minimum required code to demonstrate it?

**Comment by richieroldan** [comment]
here is a simple meteor app that adds data and doing infinite scroll. If you click the "go to other page" and try to scroll you'll see the error

Sample app
https://github.com/richieroldan/infinite-scroll-test.git

Im using Meteor 1.4.2.3 and Flow router

**Comment by abecks** [comment]
I just published 1.0.2 with a fix for this. Thanks for the demo app.
