### ISSUE TITLE
Accessing limit variable

### ISSUE THREAD

**Issue by mizsha** [abecks/meteor-infinite-scroll#16]
Currently is not possible to access the limit variable from module. Any ideas to realize request ?

Vision is:

...
  uploadedFiles: function () {
    return Images.find({}, {
      sort: {'meta.createdAt': -1}, limit: **Template.instance().infiniteScroll.limit**,
    });
  },
...

Thanks

**Comment by abecks** [comment]
Why do you want to use the limit variable there? Aren't you using infiniteScroll to power the subscription to the Images collection anyway? It will already be limited by the publication.

**Comment by mizsha** [comment]
Because if there is any other subscriptions on page, infiniteScroll display all fetched records from Images collection. And this is why i need that, because infiniteScroll subscribe for 20 records, byt displays more.

**Comment by abecks** [comment]
I've published 1.0.3 with a new `getLimit()` method, used like: `Template.instance().infiniteScroll.getLimit()`. This is a reactive data source.
