### ISSUE TITLE
The scroll doesn't trigger

### ISSUE THREAD

**Issue by cosmin-novac** [abecks/meteor-infinite-scroll#18]
I tried all possible containers, but after the first 10 elements load on the page in the beginning, the rest simply won't trigger. Nothing happens when I reach the bottom of my div/container/window. How can I check what's going on under the hood?

This is my code: 

```
    this.infiniteScroll({
      perPage: 10,
      query: {
          categoryId: categoryData._id
      },
      collection: 'debates',
      publication: 'CategoryInfiniteScroll',
      container: '#page-content-wrapper'
    });
```

The helper:
```
debate: function() {
      console.log(Template.instance().getLimit());
      //console.log(this.debate.count());
        return Collections.Debates.find({categoryId: this.category._id},{limit:Template.instance().getLimit(), sort: { rank: 1 }});;
    },    
```
And the publisher:

```
Meteor.publish('CategoryInfiniteScroll', function(limit, query) {
        var selector = {};
        check(limit, Number);
        check(query.categoryId, String);
        selector.categoryId = query.categoryId;

        return Collections.Debates.find(selector, {
          limit: limit,
          sort: {
            rank: 1
          }
        });
    });
```

**Comment by abecks** [comment]
If you clone this repository to your {PROJECT ROOT}/packages/ folder, it will be used in your app instead of the one pulled from Atmosphere. You can then debug the package by editing it's source. I dont have much time right now but I'll try to get to this when I can. In the meantime, feel free to diagnose and submit a PR.

**Comment by cosmin-novac** [comment]
Sorry, I gave up on this package altogether and solved my infiniteScroll 'manually' with publishing limits

**Comment by rpalagiri-dm** [comment]
@tenshis Can you tell me your solution, I am having the same issue.

**Comment by srpf** [comment]
@abecks I am having the same issue, help me please. 🆘
