### ISSUE TITLE
Package with no access to check package

### ISSUE THREAD

**Issue by liberatomota-itcenter** [abecks/meteor-infinite-scroll#2]
Hello,

I'm getting a error with a dependency: 
TypeError: check is not a function
    at infiniteScroll (infinite-scroll.js:66)
....

I have intalled the check package after and the error persists.
Maybe must be added to the package dependencies in the "api.uses"?

Best regards

**Comment by abecks** [comment]
Should be fixed in 0.7.2.
Sorry about that!
