### ISSUE TITLE
app is not defined ?

### ISSUE THREAD

**Issue by mikepaszkiewicz** [abecks/meteor-infinite-scroll#4]
Why is the package looking at an app.collections object when running the find() per the docs / code? I've never seen this pattern before, should just be doing a query the normal way?

**Comment by abecks** [comment]
It should. I need to fix this but short on time. Feel free to submit a PR

**Comment by mikepaszkiewicz** [comment]
Will take care of this today - super fast response, much appreciated mate!

Mike Paszkiewicz
Cofounder & COO, Habitat LLC
443-216-9367 tel:443-216-9367 | mike@tryhabitat.com mailto:mike@tryhabitat.com | tryhabitat.com http://tryhabitat.com/ | Philadelphia, PA
 http://facebook.com/mikepaszkiewicz  http://www.linkedin.com/in/michael-paszkiewicz-07053283

**Comment by abecks** [comment]
Should be fixed now with #5
